<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SEGOBRA extends Model
{
    protected $table = 'SEGOBRA';

    protected $fillable = [
        'SEOBId',
        'SEOBEmpr',
        'SEOBViv',
        'SEOBNCont',
        'SEOBProgr',
        'SEOBProy',
        'SEOBFisc',
        'SEOBSuper',
        'SEOBFecCo',
        'SEOBFecAn',
        'SEOBMonCo',
        'SEOBMonAn',
        'SEOBAvanc',
        'SEOBPlaEO',
        'SEOBVigeC',
        'SEOBVigeS',
        'SEOBConCod',
        'SEOBEst',
        'SEOBAEjer',
        'SEOBObj',
        'SEOBObm',
        'SEOBSein',
        'SEOBSefi',
        'SEOBDetS',
        'SEOBLote',
        'SEOBActI',
        'SEOBRePr',
        'SEOBReDe',
        'SEOBUtm1',
        'SEOBUtmX',
        'SEOBUtmY',
        'SEOBConstr',
        'SEOBResNom',
        'SEOBResTel',
        'SEOBResCel',
        'SEOBFisTel',
        'SEOBFisCel',
        'SEOBMonPro',
        'SEOBApoBen',
        'SEOBDevRep',
        'SEOBNivel',
        'DptoId',
        'CiuId',
        'SEOBCodSAT',
        'SEOBFF',
        'SEOBOF',
        'SEOBFisAva',
        'SEOBFisFec',
        'SEOBSupAva',
        'SEOBSupFec',
        'SEOBSeVCum',
        'SEOBSeVAnt',
        'SEOBSeVAcc',
        'SEOBSeVTer',
        'SEOBSeVRie',
        'SEOBAdePEO',
        'SEOBAdPEOV',
        'SEOBLocal',
        'SEOBAdmin',
        'SEOBPlan',
        'SEOBJefCel',
        'SEOBJefTel',
        'SEOBJefObr',
        'SEOBSupCel',
        'SEOBSupTel',
        'SEOBPtoNro',
        'SEOBSeV2De',
        'SEOBSeVTerr',
        'SEOBIdDNCP',
        'SEOBCtaCte',
        'SEOBPadron',
        'SEOBFinca',
        'SEOBVivEnt',
        'SEOBRDef',
        'SEOBRProv',
        'SEOBAcIn',
        'SEOBAnt',
        'SEOBCont',
        'SEOBVivInR',
        'SEOBVivEje',
        'SEOBVivCul',
        'SEOBSaldo',
        'SEOBAntTerr',
        'SEOBVivEntFec',
        'SEOBAdjFec',
        'SEOBAdjRes',
        'SEOBPylCod',
        'SEOBResFecResc',
        'SEOBResNroResc',
        'SEOBDocConvenio',
        'SEOBDocResResc',
        'SEOBDocResAdj',
        'SEOBDocContrato',
        'SEOBDocActIni',
        'SEOBDocRecProv',
        'SEOBDocRecDef',
        'EmpSatCod',
        'SupervCod',
        'FiscalCod',
        'SEOBFisDiasUltInf',
        'SEOBModFch',
        'SEOBModUsu',
        'SEOBAltaFch',
        'SEOBAltaUsu',
        'SEOBPreDpto',
        'SEOBPrePry',
        'SEOBPreSub',
        'SEOBPrePrg',
        'SEOBPreTip',
        'SEOBAtrasos',
        'SEOBSTPMH',
        'SEOBIdFase1',
        'SEOBEtapa',
        'SEOBEvTe',
        'SEOBInfS',
        'SEOBVTA',
        'SEOBTerr',
        'SEOBNroExpS',
        'SEOBNroExp',
        'SEOBVivPara',
        'SEOBVivResc',
        'SEOBVivAnul',
        'SEOBPuOr',
        'SEOBCanMujer',
        'SEOBCanHombre',
        'SEOBCanHijas',
        'SEOBCanHijos',
        'SEOBCanTercEdad',
        'SEOBCanPadreSol',
        'SEOBCanMadreSol',
        'SEOBCanPCD',
        'SEOBCanPO',
        'SEOBVivEnProy',
    
    ];
    
    
    protected $dates = [
        'SEOBFecCo',
        'SEOBFecAn',
        'SEOBPlaEO',
        'SEOBVigeS',
        'SEOBSein',
        'SEOBActI',
        'SEOBRePr',
        'SEOBReDe',
        'SEOBFisFec',
        'SEOBSupFec',
        'SEOBSeVCum',
        'SEOBSeVAnt',
        'SEOBSeVAcc',
        'SEOBSeVTer',
        'SEOBSeVRie',
        'SEOBAdePEO',
        'SEOBAdPEOV',
        'SEOBSeV2De',
        'SEOBSeVTerr',
        'SEOBVivEntFec',
        'SEOBAdjFec',
        'SEOBResFecResc',
        'SEOBModFch',
        'SEOBAltaFch',
    
    ];
    public $timestamps = false;
    
    protected $appends = ['resource_url'];

    /* ************************ ACCESSOR ************************* */

    public function getResourceUrlAttribute()
    {
        return url('/admin/s-e-g-o-b-r-a-s/'.$this->getKey());
    }
}
